// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID     `json:"id"`
	PostID    uuid.NullUUID `json:"post_id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	Text      string        `json:"text"`
	CreatedAt time.Time     `json:"created_at"`
}

type Course struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

type Follow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Hashtag struct {
	ID  uuid.UUID `json:"id"`
	Tag string    `json:"tag"`
}

type Like struct {
	UserID    uuid.UUID `json:"user_id"`
	PostID    uuid.UUID `json:"post_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Module struct {
	ID       uuid.UUID     `json:"id"`
	CourseID uuid.NullUUID `json:"course_id"`
	Title    string        `json:"title"`
	Order    int32         `json:"order"`
}

type Notification struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.NullUUID   `json:"user_id"`
	Type        string          `json:"type"`
	EntityID    uuid.NullUUID   `json:"entity_id"`
	PayloadJson json.RawMessage `json:"payload_json"`
	ReadAt      sql.NullTime    `json:"read_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Post struct {
	ID        uuid.UUID     `json:"id"`
	AuthorID  uuid.NullUUID `json:"author_id"`
	Text      string        `json:"text"`
	CourseID  uuid.NullUUID `json:"course_id"`
	ModuleID  uuid.NullUUID `json:"module_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type PostHashtag struct {
	PostID    uuid.UUID `json:"post_id"`
	HashtagID uuid.UUID `json:"hashtag_id"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Bio          sql.NullString `json:"bio"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    time.Time      `json:"created_at"`
}
