// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateFollow(ctx context.Context, arg CreateFollowParams) error
	CreateHashtag(ctx context.Context, tag string) (Hashtag, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) error
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePostHashtag(ctx context.Context, arg CreatePostHashtagParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	DeleteCourse(ctx context.Context, id uuid.UUID) error
	DeleteFollow(ctx context.Context, arg DeleteFollowParams) error
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	DeleteModule(ctx context.Context, id uuid.UUID) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeletePostHashtags(ctx context.Context, postID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllCourses(ctx context.Context) ([]Course, error)
	GetAllHashtags(ctx context.Context) ([]Hashtag, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error)
	GetCommentsByPostID(ctx context.Context, arg GetCommentsByPostIDParams) ([]GetCommentsByPostIDRow, error)
	GetCommentsCount(ctx context.Context, postID uuid.NullUUID) (int64, error)
	GetCourseByID(ctx context.Context, id uuid.UUID) (Course, error)
	GetFeedPosts(ctx context.Context, arg GetFeedPostsParams) ([]GetFeedPostsRow, error)
	GetFollowByUsers(ctx context.Context, arg GetFollowByUsersParams) (Follow, error)
	GetFollowers(ctx context.Context, followeeID uuid.UUID) ([]GetFollowersRow, error)
	GetFollowersCount(ctx context.Context, followeeID uuid.UUID) (int64, error)
	GetFollowing(ctx context.Context, followerID uuid.UUID) ([]GetFollowingRow, error)
	GetFollowingCount(ctx context.Context, followerID uuid.UUID) (int64, error)
	GetHashtagByID(ctx context.Context, id uuid.UUID) (Hashtag, error)
	GetHashtagByTag(ctx context.Context, tag string) (Hashtag, error)
	GetHashtagsByPost(ctx context.Context, postID uuid.UUID) ([]Hashtag, error)
	GetLikeByUserAndPost(ctx context.Context, arg GetLikeByUserAndPostParams) (Like, error)
	GetLikesByPost(ctx context.Context, postID uuid.UUID) ([]GetLikesByPostRow, error)
	GetLikesByUser(ctx context.Context, arg GetLikesByUserParams) ([]GetLikesByUserRow, error)
	GetLikesCount(ctx context.Context, postID uuid.UUID) (int64, error)
	GetModuleByID(ctx context.Context, id uuid.UUID) (Module, error)
	GetModulesByCourse(ctx context.Context, courseID uuid.NullUUID) ([]Module, error)
	GetNotificationsByUser(ctx context.Context, arg GetNotificationsByUserParams) ([]Notification, error)
	GetNotificationsCount(ctx context.Context, userID uuid.NullUUID) (int64, error)
	GetPopularPosts(ctx context.Context, arg GetPopularPostsParams) ([]GetPopularPostsRow, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostWithCounts(ctx context.Context, id uuid.UUID) (GetPostWithCountsRow, error)
	GetPostsByAuthor(ctx context.Context, arg GetPostsByAuthorParams) ([]Post, error)
	GetPostsByCourse(ctx context.Context, arg GetPostsByCourseParams) ([]GetPostsByCourseRow, error)
	GetPostsByHashtag(ctx context.Context, arg GetPostsByHashtagParams) ([]GetPostsByHashtagRow, error)
	GetPostsByModule(ctx context.Context, arg GetPostsByModuleParams) ([]GetPostsByModuleRow, error)
	GetUnreadNotifications(ctx context.Context, userID uuid.NullUUID) ([]Notification, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]User, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.NullUUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
